- name: Create config directory
  file: path="{{ app_root_dir }}/nginx" state=directory

- name: Create conf.d directory
  file: path="{{ app_root_dir }}/nginx/conf.d" state=directory

- name: Render nginx config
  template: src=nginx1.conf.j2 dest="{{ app_root_dir }}/nginx/nginx.conf"
