# Generated by Django 4.0.5 on 2022-06-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_rename_user_id_partner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
