# Generated by Django 4.0.5 on 2022-06-11 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='partner',
            name='commission',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='company_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='contract_number',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='first_name',
            field=models.CharField(default='a', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='last_name',
            field=models.CharField(default='a', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='phone_number',
            field=models.CharField(default='a', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='a', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_activated',
            field=models.DateTimeField(null=True, verbose_name='date activated'),
        ),
    ]
