# Generated by Django 4.0.5 on 2022-06-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_remove_user_username_partner_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='company_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='contract_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
