# Generated by Django 4.0.5 on 2022-06-14 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_alter_partner_commission_alter_partner_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('cost_value', models.IntegerField()),
                ('revenue', models.IntegerField()),
                ('commission', models.DecimalField(decimal_places=1, max_digits=3)),
                ('reg_date', models.DateTimeField()),
                ('expire_date', models.DateTimeField()),
                ('tariff', models.CharField(max_length=32)),
                ('quotas', models.JSONField()),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partner')),
            ],
        ),
    ]
