# Generated by Django 4.0.5 on 2022-06-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_alter_user_last_login_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='expire_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='revenue',
        ),
        migrations.AddField(
            model_name='subscription',
            name='period',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
