# Generated by Django 4.0.5 on 2022-06-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0008_remove_subscription_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='quotas',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
