# Generated by Django 4.0.5 on 2022-06-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0009_alter_subscription_quotas'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
