# Generated by Django 4.0.5 on 2022-06-28 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0011_alter_partner_inn_alter_partner_commission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='INN',
            new_name='inn',
        ),
        migrations.AlterField(
            model_name='partner',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Процент комиссии'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='company_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Наименование компании'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='commission',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Процент комиссии'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='cost_value',
            field=models.IntegerField(verbose_name='Итоговая стоимость'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partner', verbose_name='Партнёр'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='period',
            field=models.IntegerField(verbose_name='Период (мес.)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='quotas',
            field=models.JSONField(blank=True, null=True, verbose_name='Квоты'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='reg_date',
            field=models.DateTimeField(verbose_name='Дата оформления'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tariff',
            field=models.CharField(max_length=32, verbose_name='Тариф'),
        ),
    ]
